### ISSUE TITLE
feed back status Not-found by payfort

### ISSUE THREAD

**Issue by muhammadzia-se** [mage2pro/payfort-matt-jac#2]
Hi Expert,
your work is very appreciated.

url: primegroup-me.com/magento-directory

redirection urls at payfort portal:
**redirection urls:** http://primegroup-me.com/magento-directory/payfort/fort/payment/response
**Direct Transaction Feedback :** http://primegroup-me.com/magento-directory/payfort/fort/payment/response
**Notification URL:**http://primegroup-me.com/magento-directory/payfort/fort/payment/response

i installed at my eCommerce portal as mentioned above. everything is going fine but the problem is that the redirection urls are not working fine. kindly help me to resolve the issues. looking forward to your earliest response.

Regards,
Zia
![feedback](https://user-images.githubusercontent.com/24359023/39255035-9b188ea6-48bc-11e8-8cfd-22a6d89de0bf.jpg)
![redirection](https://user-images.githubusercontent.com/24359023/39255037-9b521b26-48bc-11e8-9254-517b64fd734b.jpg)

**Comment by dmitrii-fediuk** [comment]
I can fix this problem for $99.

**Comment by muhammadzia-se** [comment]
thanks for your reply. can you please give me some discount. and please confirm me below points that this extension is already covering the below points. as i told by payfort that For magento 2 we did not launch the extension.
-----------------
1- You are validating the response you are receiving from PayFort using the SHA Response value configured in your account under Security Settings. 
2- Your code handle the response parameters received on the Direct Transaction Feedback URL under Technical Settings

looking forward to your earliest response.

Thansk & Regards,
Zia

**Comment by dmitrii-fediuk** [comment]
I do not give discounts.

**Comment by muhammadzia-se** [comment]
ok Brother thanks for your time. please also confirm that is this extension covering above mentioned points!

**Comment by dmitrii-fediuk** [comment]
1) It is done here:
https://github.com/mage2pro/payfort-matt-jac/blob/1.1.0/Helper/Data.php#L654-L657
https://github.com/mage2pro/payfort-matt-jac/blob/1.1.0/Helper/Data.php#L306-L335

2) It is done here:
https://github.com/mage2pro/payfort-matt-jac/blob/1.1.0/Helper/Data.php#L670-L738

**Comment by muhammadzia-se** [comment]
Thank you very much for your valuable feedback. 
Regards,
Zia
